export const colorScheme = {
    React: "purple",
    CSS: "orange",
    HTML: "orange",
    "Node.js": "green",
    Express: "teal",
    SQL: "blue",
    "Front-end": "purple",
    "Back-end": "cyan",
    Design: "pink",
    API: "red",
    JavaScript: "yellow",
    TypeScript: "blue",
    Other: "green",
};
